from pathlib import Path
from typing import List, Protocol

class PathResolver(Protocol):
    """
    Contract for resolving filesystem paths used across the application.

    This protocol defines how different file categories (raw input,
    finalized output, and LLM-generated output) should be resolved
    into concrete `Path` objects.

    Implementations are responsible for handling directory structure,
    filename normalization, and path safety.
    """
    def raw_file(self, name: str, suffix: str = ".txt") -> Path:
        """
        Resolve the path for a raw input file.

        Args:
            name (str): Base filename without extension.
            suffix (str, optional): File extension including the leading dot.
                Defaults to ".txt".

        Returns:
            Path: Absolute or relative path pointing to the raw file location.
        """
        ...
    
    def finalized_file(
        self, 
        name: List[str], 
        input_fname: str,
        suffix: str = ".json",
    )-> Path:
        """
        Resolve the path for a finalized processed file.

        Args:
            name (List[str]): Hierarchical components used to build
                nested directories or structured filenames.
            input_fname (str): Original input filename used as reference.
            suffix (str, optional): File extension including the leading dot.
                Defaults to ".json".

        Returns:
            Path: Path pointing to the finalized output file location.
        """
        ...
    
    def temp_finalized_file(
        self,
        name: List[str], 
        input_fname: str,
        suffix: str = ".json",
    )-> Path:
        """
        Resolve the path for a file generated by an LLM process.

        Args:
            name (List[str]): Hierarchical components for directory
                or filename construction.
            input_fname (str): Original input filename used for traceability.
            suffix (str, optional): File extension including the leading dot.
                Defaults to ".json".

        Returns:
            Path: Path pointing to the LLM output file location.
        """
        ...